create TABLE EVENTS_boomtrain(
EVENT_ID VARCHAR(100),
EVENT_TYPE VARCHAR(1000),
SITE_ID VARCHAR(1000),
BSIN VARCHAR(100),
EMAIL VARCHAR(1000),
USER_ID VARCHAR(1000),
PROPERTIES JSON,
DT datetime,
ETL_TIME datetime
)
DISTRIBUTED BY HASH(dt, EVENT_TYPE)

